name: Resolver CI Completion Notification

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: ${{ secrets.SLACK_CHANNEL_NAME }}
          slack_username: ${{ secrets.SLACK_USERNAME }}
        if: success()
